import type { Metadata } from "next";
import { Inter } from "next/font/google";

// These styles apply to every route in the application.
import "@/styles/globals.css";

// If loading a variable font, you don't need to specify the font weight.
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
